Repository julianyeo/Metrics-for-health-Node-backend, pull requests merged in 2023-03, with the labels that each got.

#1 feat controller
  controllers/auth.js
  controllers/metrics.js
Labels: infra

#2 remove mongodb uri
  server.js
Labels: bug

#4 remove client build
  client/build/asset-manifest.json
  client/build/assets/auth-illustration.svg
  client/build/assets/logo.svg
  client/build/favicon-16x16.png
  client/build/favicon-32x32.png
  client/build/favicon.ico
  client/build/index.html
  client/build/manifest.json
  client/build/robots.txt
  client/build/static/css/main.444d7474.css
  client/build/static/css/main.444d7474.css.map
  client/build/static/js/496.85453718.chunk.js
  client/build/static/js/496.85453718.chunk.js.LICENSE.txt
  client/build/static/js/496.85453718.chunk.js.map
  client/build/static/js/787.59db3541.chunk.js
  client/build/static/js/787.59db3541.chunk.js.map
  client/build/static/js/main.81495fc3.js
  client/build/static/js/main.81495fc3.js.LICENSE.txt
  client/build/static/js/main.81495fc3.js.map
  client/build/static/js/main.a6c014bd.js
  client/build/static/js/main.a6c014bd.js.LICENSE.txt
  client/build/static/js/main.a6c014bd.js.map
Labels: duplicate

#6 commit auth.js
  routes/auth.js
Labels: documentation

#7 remove comment
  server.js
Labels: documentation, good first issue
